# Generated by Django 3.2.16 on 2023-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='이름')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('part', models.CharField(max_length=20, verbose_name='파트')),
                ('team', models.CharField(max_length=20, verbose_name='팀')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
