# Generated by Django 3.2.16 on 2023-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partvote',
            field=models.BooleanField(default=False, verbose_name='파트장투표 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teamvote',
            field=models.BooleanField(default=False, verbose_name='팀투표 여부'),
        ),
    ]
