# Generated by Django 3.2.16 on 2023-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cname', models.CharField(max_length=30, unique=True)),
                ('part', models.CharField(choices=[('BE', 'BE'), ('FE', 'FE')], max_length=2)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tname', models.CharField(choices=[('DANSUPPORT', 'Dansupport'), ('REPICK', 'Repick'), ('THERAPEASE', 'TherapEase'), ('HOOKING', 'Hooking'), ('BARIBARI', 'BariBari')], max_length=30, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
