# Generated by Django 3.2.16 on 2023-06-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='파트장 후보 이름')),
                ('part', models.CharField(max_length=20, verbose_name='파트')),
                ('vote_cnt', models.IntegerField(default=0, verbose_name='투표 횟수')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.CharField(max_length=20, unique=True, verbose_name='팀이름')),
                ('vote_cnt', models.IntegerField(default=0, verbose_name='투표 횟수')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='ceos', max_length=20, verbose_name='투표자이름')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamVoteTeamPk', to='vote.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='ceos', max_length=20, verbose_name='투표자이름')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CandidateVoteCandidatePk', to='vote.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
