# Generated by Django 3.2.16 on 2023-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvote',
            name='user_name',
            field=models.CharField(default='ceos', max_length=20, verbose_name='투표자이름'),
        ),
    ]
