# Generated by Django 3.2.16 on 2023-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_teamvote_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamvote',
            name='user_id',
        ),
    ]
