# Generated by Django 3.0.8 on 2023-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('front', 'Front-end'), ('back', 'Back-end')], max_length=10)),
                ('userName', models.CharField(max_length=10)),
                ('voteNum', models.IntegerField(default=0)),
                ('candidate', models.CharField(choices=[('황재령', '황재령'), ('김현우', '김현우'), ('노수진', '노수진'), ('서혜준', '서혜준'), ('최민주', '최민주'), ('서찬혁', '서찬혁'), ('김서연', '김서연'), ('최유미', '최유미'), ('배성준', '배성준'), ('김현수', '김현수'), ('임탁균', '임탁균'), ('권가은', '권가은'), ('김문기', '김문기'), ('이소정', '이소정'), ('장효신', '장효신'), ('조예지', '조예지'), ('김지원', '김지원'), ('오예린', '이예지'), ('신유진', '신유진')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='teamPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('TherapEase', 'TherapEase'), ('Dansupport', 'Dansupport'), ('RePick', 'Repick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking')], max_length=10)),
                ('description', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(max_length=10)),
                ('voteNum', models.IntegerField(default=0)),
            ],
        ),
    ]
