# Generated by Django 4.2.2 on 2023-06-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partpoll',
            old_name='name',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='partpoll',
            name='candidate',
            field=models.CharField(choices=[('노수진', '노수진'), ('권가은', '권가은'), ('김문기', '김문기'), ('서찬혁', '서찬혁'), ('김현우', '김현우'), ('신유진', '신유진'), ('조예지', '조예지'), ('서혜준', '서혜준'), ('김지원', '김지원'), ('최유미', '최유미'), ('김서연', '김서연'), ('황재령', '황재령'), ('오예린', '이예지'), ('임탁균', '임탁균'), ('최민주', '최민주'), ('김현수', '김현수'), ('배성준', '배성준'), ('이소정', '이소정'), ('장효신', '장효신')], max_length=10),
        ),
    ]
