# Generated by Django 3.0.8 on 2023-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpoll',
            name='candidate',
            field=models.CharField(choices=[('김서연', '김서연'), ('서혜준', '서혜준'), ('김지원', '김지원'), ('김현우', '김현우'), ('김문기', '김문기'), ('최유미', '최유미'), ('김현수', '김현수'), ('오예린', '이예지'), ('최민주', '최민주'), ('조예지', '조예지'), ('배성준', '배성준'), ('서찬혁', '서찬혁'), ('신유진', '신유진'), ('권가은', '권가은'), ('장효신', '장효신'), ('이소정', '이소정'), ('노수진', '노수진'), ('황재령', '황재령'), ('임탁균', '임탁균')], max_length=10),
        ),
    ]
