# Generated by Django 3.2.16 on 2023-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partpoll',
            old_name='name',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='partpoll',
            name='candidate',
            field=models.CharField(choices=[('임탁균', '임탁균'), ('권가은', '권가은'), ('김현우', '김현우'), ('노수진', '노수진'), ('신유진', '신유진'), ('김서연', '김서연'), ('장효신', '장효신'), ('김지원', '김지원'), ('오예린', '이예지'), ('최민주', '최민주'), ('황재령', '황재령'), ('최유미', '최유미'), ('서찬혁', '서찬혁'), ('배성준', '배성준'), ('김현수', '김현수'), ('서혜준', '서혜준'), ('이소정', '이소정'), ('조예지', '조예지'), ('김문기', '김문기')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partpoll',
            name='part',
            field=models.CharField(choices=[('back', 'Back-end'), ('front', 'Front-end')], max_length=10),
        ),
    ]
