# Generated by Django 3.2.16 on 2023-06-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230624_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpoll',
            name='candidate',
            field=models.CharField(choices=[('임탁균', '임탁균'), ('장효신', '장효신'), ('서찬혁', '서찬혁'), ('김지원', '김지원'), ('권가은', '권가은'), ('김현우', '김현우'), ('이소정', '이소정'), ('오예린', '이예지'), ('김서연', '김서연'), ('서혜준', '서혜준'), ('황재령', '황재령'), ('노수진', '노수진'), ('최민주', '최민주'), ('조예지', '조예지'), ('김문기', '김문기'), ('최유미', '최유미'), ('신유진', '신유진'), ('김현수', '김현수'), ('배성준', '배성준')], max_length=10),
        ),
    ]
